version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/simple-life
      - JWT_SECRET=simple-life-secret-key-2024
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 